// Regenerates supabase/seed.sql from the demo data in src/lib/demo.
// Usage: npm run seed:generate
import { writeFileSync } from "node:fs";
import { demoClubs } from "../src/lib/demo/clubs.ts";
import { demoEvents } from "../src/lib/demo/events.ts";
import { demoAnnouncements } from "../src/lib/demo/announcements.ts";
import { demoDiscussions } from "../src/lib/demo/discussions.ts";
import { demoOpportunities } from "../src/lib/demo/opportunities.ts";

const AUTHORED_ON = Date.parse("2026-09-21");

const q = (v: string | number | boolean | null | undefined): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  return `'${v.replace(/'/g, "''")}'`;
};
const arr = (xs: string[]) => `array[${xs.map(q).join(", ")}]::text[]`;
const offset = (iso: string) => Math.round((Date.parse(iso.slice(0, 10)) - AUTHORED_ON) / 86_400_000);

function to24h(t: string) {
  const m = t.match(/(\d+):(\d+)\s*(AM|PM)/i)!;
  const h = (+m[1] % 12) + (m[3].toUpperCase() === "PM" ? 12 : 0);
  return `${String(h).padStart(2, "0")}:${m[2]}`;
}
// Timestamps are relative to the day the seed runs, so a fresh database always has an upcoming week.
const at = (dayOffset: number, hhmm: string) =>
  `((current_date + ${dayOffset}) + time '${hhmm}') at time zone 'Asia/Kolkata'`;
const club = (slug: string) => `(select id from public.clubs where slug = ${q(slug)})`;

const out: string[] = ["-- Generated by scripts/generate-seed.mts. Do not edit by hand.", ""];

for (const c of demoClubs) {
  out.push(
    `insert into public.clubs (slug, name, short_name, tagline, description, category, color, member_count, founded_year, external_link, instagram_link, leads, tags, featured) values (${[
      q(c.slug), q(c.name), q(c.shortName), q(c.tagline), q(c.description), q(c.category), q(c.color),
      c.memberCount, c.foundedYear, q(c.externalLink), q(c.instagramLink), `${q(JSON.stringify(c.leads))}::jsonb`,
      arr(c.tags), c.featured,
    ].join(", ")});`,
  );
}
out.push("");

for (const e of demoEvents) {
  out.push(
    `insert into public.events (club_id, title, description, type, starts_at, ends_at, venue, registration_link, max_seats, tags, featured) values (${[
      club(e.clubSlug), q(e.title), q(e.description), q(e.type), at(offset(e.date), to24h(e.time)),
      e.endTime ? at(offset(e.date), to24h(e.endTime)) : "null", q(e.venue), q(e.registrationLink),
      e.maxSeats ?? "null", arr(e.tags), e.featured,
    ].join(", ")});`,
  );
}
out.push("");

for (const a of demoAnnouncements) {
  out.push(
    `insert into public.announcements (club_id, title, body, priority, pinned, author_name, created_at) values (${[
      club(a.clubSlug), q(a.title), q(a.body), q(a.priority), a.pinned, q(a.author), at(offset(a.postedAt), a.postedAt.slice(11, 16)),
    ].join(", ")});`,
  );
}
out.push("");

for (const d of demoDiscussions) {
  out.push(
    `insert into public.discussions (author_name, author_year, title, body, category, subcategory, tags, pinned, solved, created_at) values (${[
      q(d.author), q(d.authorYear), q(d.title), q(d.body), q(d.category), q(d.subcategory), arr(d.tags), d.pinned,
      d.solved ?? false, at(offset(d.postedAt), d.postedAt.slice(11, 16)),
    ].join(", ")});`,
  );
}
out.push("");

for (const o of demoOpportunities) {
  out.push(
    `insert into public.opportunities (title, type, organizer, deadline, eligibility, prize, stipend, description, link, tags, featured) values (${[
      q(o.title), q(o.type), q(o.organizer), `current_date + ${offset(o.deadline)}`, q(o.eligibility), q(o.prize),
      q(o.stipend), q(o.description), q(o.link), arr(o.tags), o.featured,
    ].join(", ")});`,
  );
}

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), out.join("\n") + "\n");
console.log(`Wrote supabase/seed.sql (${out.length} lines)`);
