import type { Achievement } from "@/lib/types";

export const demoAchievements: Achievement[] = [
  {
    id: "ac1",
    title: "1st Place, Hackdata 2026",
    people: "Joyce Malik",
    team: "Team NeuralFlow",
    clubSlug: "10x-club",
    category: "hackathon",
    achievedOn: "2026-08-12",
    description: "Won first place with an AI-powered aquaculture monitoring system.",
    verified: true,
  },
  {
    id: "ac2",
    title: "Google Cloud Professional Cloud Architect",
    people: "Rahul Nair",
    clubSlug: "gdg-ait",
    category: "certification",
    achievedOn: "2026-07-20",
    description: "Earned the Professional Cloud Architect certification.",
    verified: true,
  },
  {
    id: "ac3",
    title: "Smart India Hackathon, national top 10",
    people: "Meera Iyer and team",
    clubSlug: "nextion-x",
    category: "competition",
    achievedOn: "2026-06-15",
    description: "Reached the national top 10 with an EdTech solution.",
    verified: true,
  },
  {
    id: "ac4",
    title: "Inter-college Go-Kart Championship, runners-up",
    people: "Motor Sports Club racing team",
    clubSlug: "motor-sports",
    category: "sports",
    achievedOn: "2026-08-30",
    description: "Finished second overall in the state inter-college go-kart championship.",
    verified: true,
  },
  {
    id: "ac5",
    title: "Paper published at IEEE IROS 2026",
    people: "Suresh Kumar",
    clubSlug: "ait-robotics",
    category: "research",
    achievedOn: "2026-07-05",
    description: "Published work on autonomous navigation for indoor robots.",
    verified: true,
  },
  {
    id: "ac6",
    title: "Best UI/UX, DesignHack 2026",
    people: "Ananya Pillai",
    clubSlug: "nextion-x",
    category: "design",
    achievedOn: "2026-09-01",
    description: "Won Best UI/UX for an accessibility-first mobile app.",
    verified: false,
  },
];
