import type { Announcement } from "@/lib/types";

export const demoAnnouncements: Announcement[] = [
  {
    id: "a1",
    title: "SIH Internal Qualifier — Registrations Close Tonight",
    body: "Last chance to register for the Smart India Hackathon internal qualifier. Registrations close at 11:59 PM. Form your team of 4–6 and register via the link below. Problem statements are now live.",
    clubSlug: "nextion-x",
    clubName: "Nextion X",
    clubColor: "#6B4A7A",
    priority: "urgent",
    postedAt: "2026-09-21T14:00:00",
    author: "Akash Reddy",
    pinned: true,
  },
  {
    id: "a2",
    title: "Android Workshop — Seats Almost Full",
    body: "Only 17 seats remaining for the Android Development Workshop this week. Register now to confirm your spot. Bring your laptop with Android Studio installed.",
    clubSlug: "gdg-ait",
    clubName: "GDG AIT",
    clubColor: "#3F6E8C",
    priority: "important",
    postedAt: "2026-09-21T10:30:00",
    author: "Rahul Nair",
    pinned: false,
  },
  {
    id: "a3",
    title: "BAJA SAE — Chassis Build Schedule Updated",
    body: "Assembly sessions now start at 3:00 PM on Sundays (shifted from 2:00 PM). Engine testing will be done on Wednesdays. Come to Block D workshop if you want to join the build team.",
    clubSlug: "motor-sports",
    clubName: "Motor Sports Club",
    clubColor: "#B5532E",
    priority: "info",
    postedAt: "2026-09-20T18:00:00",
    author: "Vikram Singh",
    pinned: false,
  },
  {
    id: "a4",
    title: "10X Weekly — This Week's Theme: Deep Work",
    body: "This week's standup theme is Deep Work. Come prepared to share your strategy for distraction-free focused work. Cal Newport's Deep Work chapter summary will be discussed.",
    clubSlug: "10x-club",
    clubName: "10X Club",
    clubColor: "#C8902E",
    priority: "info",
    postedAt: "2026-09-20T09:00:00",
    author: "Joyce Malik",
    pinned: false,
  },
  {
    id: "a5",
    title: "Robotics Workshop — Pre-reading Material Released",
    body: "Pre-reading material for the ROS 2 workshop has been uploaded. Please go through the ROS 2 basics PDF before the session this weekend. Hands-on time will be more productive if you're familiar with the concepts.",
    clubSlug: "ait-robotics",
    clubName: "AIT Robotics",
    clubColor: "#A8642A",
    priority: "info",
    postedAt: "2026-09-19T16:00:00",
    author: "Suresh Kumar",
    pinned: false,
  },
  {
    id: "a6",
    title: "FPV Night Flying — Guest Pilots Confirmed",
    body: "Two guest FPV pilots from the Bengaluru drone racing circuit will fly LED-rigged quads at our night demo. Bring your own quad if you have one; we'll have spare batteries and a safety briefing at 5:45.",
    clubSlug: "uav-club",
    clubName: "UAV Club",
    clubColor: "#5E7A3A",
    priority: "important",
    postedAt: "2026-09-18T11:00:00",
    author: "Kavya Menon",
    pinned: false,
  },
];
