import type { Club } from "@/lib/types";

export const demoClubs: Club[] = [
  {
    id: "1",
    slug: "10x-club",
    name: "10X Club",
    shortName: "10X",
    tagline: "Level up by 10x every single day",
    description:
      "10X Club is AIT's flagship growth and productivity club. We believe in compounding improvement — workshops on productivity, personal development, tech deep-dives, and building the mindset to grow 10x every year.",
    category: "technical",
    color: "#C8902E",
    memberCount: 120,
    foundedYear: 2021,
    instagramLink: "https://instagram.com",
    leads: [
      { name: "Joyce Malik", role: "President" },
      { name: "Arjun Shetty", role: "Secretary" },
    ],
    tags: ["Productivity", "Growth", "Workshops", "Tech"],
    featured: true,
  },
  {
    id: "2",
    slug: "gdg-ait",
    name: "GDG AIT",
    shortName: "GDG",
    tagline: "Google Developer Group at AIT",
    description:
      "Google Developer Group at Dr. AIT — a community for developers who are interested in Google's developer technology. We run workshops, study jams, hackathons, and connect students to the global GDG community.",
    category: "technical",
    color: "#3F6E8C",
    memberCount: 200,
    foundedYear: 2019,
    externalLink: "https://gdg.community.dev",
    instagramLink: "https://instagram.com",
    leads: [
      { name: "Rahul Nair", role: "Lead" },
      { name: "Priya Sharma", role: "Co-Lead" },
    ],
    tags: ["Google", "Android", "Cloud", "Web", "AI/ML"],
    featured: true,
  },
  {
    id: "3",
    slug: "nextion-x",
    name: "Nextion X",
    shortName: "NX",
    tagline: "Building the next generation of innovators",
    description:
      "Nextion X is AIT's innovation and entrepreneurship club. We bridge the gap between ideas and execution — startup pitches, incubation support, design thinking workshops, and industry mentorship.",
    category: "technical",
    color: "#6B4A7A",
    memberCount: 85,
    foundedYear: 2022,
    instagramLink: "https://instagram.com",
    leads: [
      { name: "Akash Reddy", role: "President" },
      { name: "Sneha Joshi", role: "VP" },
    ],
    tags: ["Startup", "Innovation", "Design Thinking", "Entrepreneurship"],
    featured: true,
  },
  {
    id: "4",
    slug: "uav-club",
    name: "UAV Club",
    shortName: "UAV",
    tagline: "We build things that fly",
    description:
      "AIT's drone and autonomous systems club. We design, build, and program UAVs from scratch — racing drones, fixed-wing aircraft, FPV builds, and autonomous flight controllers. If it flies, we're obsessed with it.",
    category: "technical",
    color: "#5E7A3A",
    memberCount: 75,
    foundedYear: 2020,
    instagramLink: "https://instagram.com",
    leads: [
      { name: "Kavya Menon", role: "President" },
      { name: "Rohan Das", role: "Chief Pilot" },
    ],
    tags: ["Drones", "FPV", "Autonomous", "Hardware", "Flight"],
    featured: true,
  },
  {
    id: "5",
    slug: "motor-sports",
    name: "Motor Sports Club",
    shortName: "MSC",
    tagline: "Built for speed. Driven by passion.",
    description:
      "AIT's Motor Sports Club builds and races formula-style vehicles, go-karts, and off-road buggies. We compete in national BAJA SAE, Formula Bharat, and Go-Kart Championship events. Mechanics, designers, and drivers all welcome.",
    category: "sports",
    color: "#B5532E",
    memberCount: 110,
    foundedYear: 2018,
    instagramLink: "https://instagram.com",
    leads: [
      { name: "Vikram Singh", role: "Team Captain" },
      { name: "Divya Krishnan", role: "Chief Engineer" },
    ],
    tags: ["BAJA SAE", "Formula", "Go-Kart", "Mechanical", "Racing"],
    featured: true,
  },
  {
    id: "6",
    slug: "ait-robotics",
    name: "AIT Robotics",
    shortName: "ROBO",
    tagline: "Building intelligent machines",
    description:
      "AIT Robotics Club brings together students passionate about robotics, embedded systems, and automation. We build robots, participate in national competitions, and run hands-on hardware workshops.",
    category: "technical",
    color: "#A8642A",
    memberCount: 60,
    foundedYear: 2023,
    leads: [
      { name: "Suresh Kumar", role: "Lead" },
      { name: "Ananya Pillai", role: "Co-Lead" },
    ],
    tags: ["Robotics", "IoT", "Embedded Systems", "Arduino", "ROS"],
    featured: false,
  },
];
