import type { Discussion } from "@/lib/types";

export const demoDiscussions: Discussion[] = [
  {
    id: "d1",
    title: "Does anyone have DBMS PYQs from 2023–24?",
    body: "Looking for previous year question papers for DBMS (3rd sem CSE). I've checked the library but couldn't find them. Any Google Drive links would be super helpful.",
    author: "Aditya Rao",
    authorYear: "3rd Sem CSE",
    category: "academic",
    subcategory: "CSE",
    postedAt: "2026-09-21T08:00:00",
    upvotes: 34,
    replyCount: 12,
    tags: ["DBMS", "PYQ", "CSE", "3rd Sem"],
    pinned: false,
    solved: true,
  },
  {
    id: "d2",
    title: "Anyone interested in teaming up for SIH?",
    body: "Looking for 3 more people to form a team for the SIH internal qualifier. I have experience in ML and backend. Looking for frontend dev + hardware/IoT person + domain expert. DM me or reply here.",
    author: "Meera Iyer",
    authorYear: "5th Sem CSE",
    category: "projects",
    subcategory: "Hackathons",
    postedAt: "2026-09-20T22:00:00",
    upvotes: 48,
    replyCount: 23,
    tags: ["SIH", "Hackathon", "Team", "ML"],
    pinned: true,
    solved: false,
  },
  {
    id: "d3",
    title: "Which electives should I take in 5th sem?",
    body: "Choosing between Machine Learning, Computer Networks, and Cryptography. Any seniors who've taken these? Which one has better scope for placements and actual learning?",
    author: "Krishnam Murty",
    authorYear: "4th Sem CSE",
    category: "academic",
    subcategory: "CSE",
    postedAt: "2026-09-19T15:00:00",
    upvotes: 71,
    replyCount: 31,
    tags: ["Electives", "5th Sem", "Placements"],
    pinned: false,
    solved: false,
  },
  {
    id: "d4",
    title: "Should we start a robotics club for ECE students?",
    body: "ECE students barely get a chance to work on actual robotics projects. The existing Robotics Club is mostly CSE-focused. Should we petition for a separate ECE-oriented robotics and embedded systems club?",
    author: "Tanvir Ahmed",
    authorYear: "4th Sem ECE",
    category: "campus",
    subcategory: "Clubs",
    postedAt: "2026-09-18T13:00:00",
    upvotes: 89,
    replyCount: 44,
    tags: ["ECE", "Robotics", "New Club", "Embedded"],
    pinned: false,
    solved: false,
  },
  {
    id: "d5",
    title: "Best resources to learn React from scratch?",
    body: "Complete beginner to web dev. Tried a couple of YouTube tutorials but they go too fast. Any structured roadmap or resource you'd recommend for someone starting React in 2026?",
    author: "Pooja Kulkarni",
    authorYear: "3rd Sem ISE",
    category: "career",
    subcategory: "Web Development",
    postedAt: "2026-09-17T11:00:00",
    upvotes: 56,
    replyCount: 28,
    tags: ["React", "Web Dev", "Resources", "Beginners"],
    pinned: false,
    solved: true,
  },
  {
    id: "d6",
    title: "Can GDG conduct a Flutter workshop?",
    body: "I know GDG focuses on Android native, but Flutter is cross-platform and a lot of us want to learn it. Can GDG add a Flutter workshop to their schedule? I know at least 40 students who'd attend.",
    author: "Nikita Jain",
    authorYear: "5th Sem ISE",
    category: "campus",
    subcategory: "Clubs",
    postedAt: "2026-09-16T09:00:00",
    upvotes: 102,
    replyCount: 18,
    tags: ["Flutter", "GDG", "Workshop Request"],
    pinned: false,
    solved: false,
  },
  {
    id: "d7",
    title: "How do college placements actually work here?",
    body: "4th sem student — super confused about the placement process at AIT. When does CGPA matter? Which companies come? What's the eligibility cutoff? Any seniors who can share a clear breakdown?",
    author: "Rohan Patil",
    authorYear: "4th Sem CSE",
    category: "career",
    subcategory: "Placements",
    postedAt: "2026-09-15T20:00:00",
    upvotes: 135,
    replyCount: 52,
    tags: ["Placements", "CGPA", "Career", "Seniors"],
    pinned: false,
    solved: true,
  },
];
