import type { Event } from "@/lib/types";

export const demoEvents: Event[] = [
  {
    id: "e1",
    title: "Android Development Workshop",
    clubSlug: "gdg-ait",
    clubName: "GDG AIT",
    clubColor: "#3F6E8C",
    type: "workshop",
    date: "2026-09-24",
    time: "4:00 PM",
    endTime: "6:00 PM",
    venue: "CS Lab 3, Block A",
    description:
      "A hands-on workshop on building Android apps with Kotlin and Jetpack Compose. Bring your laptop. Beginners welcome.",
    registrationLink: "#",
    maxSeats: 60,
    registeredCount: 43,
    tags: ["Android", "Kotlin", "Jetpack Compose"],
    featured: true,
  },
  {
    id: "e2",
    title: "10X Weekly Standup",
    clubSlug: "10x-club",
    clubName: "10X Club",
    clubColor: "#C8902E",
    type: "meeting",
    date: "2026-09-22",
    time: "5:00 PM",
    endTime: "5:45 PM",
    venue: "Seminar Hall 2",
    description:
      "Weekly accountability standup. Share what you built, learned, or achieved this week.",
    registeredCount: 28,
    tags: ["Productivity", "Weekly"],
    featured: false,
  },
  {
    id: "e3",
    title: "Go-Kart Assembly Session",
    clubSlug: "motor-sports",
    clubName: "Motor Sports Club",
    clubColor: "#B5532E",
    type: "practice",
    date: "2026-09-21",
    time: "3:00 PM",
    endTime: "6:00 PM",
    venue: "Motor Sports Workshop, Block D",
    description:
      "Weekly chassis assembly and brake-testing session for our BAJA SAE vehicle. All branches welcome — mechanics, electricals, designers.",
    registeredCount: 18,
    tags: ["BAJA SAE", "Build", "Mechanical"],
    featured: false,
  },
  {
    id: "e4",
    title: "Smart India Hackathon — Internal Qualifier",
    clubSlug: "nextion-x",
    clubName: "Nextion X",
    clubColor: "#6B4A7A",
    type: "hackathon",
    date: "2026-10-04",
    time: "9:00 AM",
    endTime: "9:00 PM",
    venue: "Innovation Lab, Block C",
    description:
      "AIT's internal qualifier for Smart India Hackathon 2026. Form teams of 4–6, pick a problem statement, and present your solution. Top 3 teams represent AIT at SIH nationals.",
    registrationLink: "#",
    maxSeats: 120,
    registeredCount: 78,
    tags: ["Hackathon", "SIH", "Innovation"],
    featured: true,
  },
  {
    id: "e5",
    title: "Startup Pitch Day",
    clubSlug: "nextion-x",
    clubName: "Nextion X",
    clubColor: "#6B4A7A",
    type: "competition",
    date: "2026-09-28",
    time: "2:00 PM",
    endTime: "5:00 PM",
    venue: "Auditorium",
    description:
      "Present your startup idea to a panel of mentors and investors. 5-minute pitch + 5-minute Q&A. Cash prizes for top 3 ideas.",
    registrationLink: "#",
    maxSeats: 30,
    registeredCount: 18,
    tags: ["Startup", "Pitch", "Entrepreneurship"],
    featured: true,
  },
  {
    id: "e6",
    title: "Cloud Study Jam — GCP",
    clubSlug: "gdg-ait",
    clubName: "GDG AIT",
    clubColor: "#3F6E8C",
    type: "workshop",
    date: "2026-10-01",
    time: "3:00 PM",
    endTime: "5:30 PM",
    venue: "CS Lab 1",
    description:
      "Guided study jam on Google Cloud Platform. Complete labs, earn badges. Free tier accounts provided.",
    registrationLink: "#",
    maxSeats: 50,
    registeredCount: 31,
    tags: ["Cloud", "GCP", "DevOps"],
    featured: false,
  },
  {
    id: "e7",
    title: "Robotics Workshop — Intro to ROS",
    clubSlug: "ait-robotics",
    clubName: "AIT Robotics",
    clubColor: "#A8642A",
    type: "workshop",
    date: "2026-09-27",
    time: "10:00 AM",
    endTime: "1:00 PM",
    venue: "Robotics Lab",
    description:
      "Introduction to Robot Operating System (ROS 2). Hands-on session with actual robot hardware.",
    registrationLink: "#",
    maxSeats: 20,
    registeredCount: 19,
    tags: ["Robotics", "ROS", "Hardware"],
    featured: false,
  },
  {
    id: "e8",
    title: "FPV Night Flying — Open Demo",
    clubSlug: "uav-club",
    clubName: "UAV Club",
    clubColor: "#5E7A3A",
    type: "social",
    date: "2026-09-30",
    time: "6:00 PM",
    endTime: "8:00 PM",
    venue: "Open Air Amphitheatre",
    description:
      "LED-rigged FPV quads flying after dark, with goggles to try on. Come watch, or bring your own quad for a supervised flight. No experience needed.",
    maxSeats: 200,
    registeredCount: 112,
    tags: ["Drones", "FPV", "Demo"],
    featured: true,
  },
];
