import type { Opportunity } from "@/lib/types";

export const demoOpportunities: Opportunity[] = [
  {
    id: "o1",
    title: "Smart India Hackathon 2026",
    type: "hackathon",
    organizer: "Government of India / AICTE",
    deadline: "2026-10-15",
    eligibility: "All undergraduate students",
    prize: "₹1,00,000 for winners",
    description:
      "India's biggest national level hackathon. Solve real problems faced by central & state government ministries. 36-hour nonstop coding event.",
    link: "#",
    tags: ["National", "Government", "36hr"],
    featured: true,
  },
  {
    id: "o2",
    title: "Google Summer of Code 2027",
    type: "internship",
    organizer: "Google",
    deadline: "2027-02-01",
    eligibility: "Students 18+",
    stipend: "$3000–$6600 USD",
    description:
      "Work with an open source organization on a 3-month programming project. One of the most prestigious student programs in tech.",
    link: "#",
    tags: ["Open Source", "Google", "Remote", "Stipend"],
    featured: true,
  },
  {
    id: "o3",
    title: "ISRO Young Scientist Programme",
    type: "research",
    organizer: "ISRO",
    deadline: "2026-11-30",
    eligibility: "1st–3rd year UG students",
    description:
      "Spend 2 weeks at an ISRO centre and work on real space technology problems. One of India's most prestigious student research programs.",
    link: "#",
    tags: ["Space", "ISRO", "Research", "National"],
    featured: true,
  },
  {
    id: "o4",
    title: "Microsoft AI Classroom Series",
    type: "certification",
    organizer: "Microsoft",
    deadline: "2026-12-31",
    eligibility: "Any student",
    description:
      "Free Azure AI certification training for students. Complete online modules, earn a Microsoft certification. Fully remote.",
    link: "#",
    tags: ["AI", "Microsoft Azure", "Free", "Certification"],
    featured: false,
  },
  {
    id: "o5",
    title: "National Robotics Championship",
    type: "competition",
    organizer: "AICTE",
    deadline: "2026-10-20",
    eligibility: "Teams of 3–5 engineering students",
    prize: "₹50,000 + trophy",
    description:
      "Build and program a robot to complete a set of challenges. Autonomous + manual control rounds. Categories: line following, obstacle avoidance, arena battle.",
    link: "#",
    tags: ["Robotics", "Hardware", "Teams", "AICTE"],
    featured: false,
  },
  {
    id: "o6",
    title: "Goldman Sachs Engineering Virtual Internship",
    type: "internship",
    organizer: "Goldman Sachs",
    deadline: "2026-10-31",
    eligibility: "Pre-final year CSE/ISE students",
    stipend: "Paid",
    description:
      "Virtual internship focusing on software engineering, quantitative finance, and data science. Hands-on tasks, mentorship, and real-world experience.",
    link: "#",
    tags: ["Finance", "Software", "Virtual", "Pre-final Year"],
    featured: false,
  },
  {
    id: "o7",
    title: "INSPIRE Scholarship — DST",
    type: "scholarship",
    organizer: "Department of Science & Technology",
    deadline: "2026-11-01",
    eligibility: "Students in top 1% of 10+2",
    stipend: "₹80,000/year",
    description:
      "Scholarship for exceptional students pursuing basic or natural sciences. Covers tuition, living allowance, and research grants.",
    link: "#",
    tags: ["Scholarship", "Government", "Science"],
    featured: false,
  },
];
